Metrics/LineLength:
  Max: 160
  Exclude:
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

# Future Cops - 1.0
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
